@csrf
<div class="grid gap-6 sm:grid-cols-2">
    <div class="sm:col-span-2"><label for="name" class="text-sm font-medium text-gray-700">Nama produk</label><input id="name" name="name" type="text" value="{{ old('name', $product->name ?? '') }}" class="mt-1 block w-full rounded-lg border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500" required><x-input-error :messages="$errors->get('name')" class="mt-2" /></div>
    <div><label for="category_id" class="text-sm font-medium text-gray-700">Kategori</label><select id="category_id" name="category_id" class="mt-1 block w-full rounded-lg border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500" required><option value="">Pilih kategori</option>@foreach ($categories as $category)<option value="{{ $category->id }}" @selected(old('category_id', $product->category_id ?? '') == $category->id)>{{ $category->name }}</option>@endforeach</select><x-input-error :messages="$errors->get('category_id')" class="mt-2" /></div>
    <div><label for="image" class="text-sm font-medium text-gray-700">Foto produk</label><input id="image" name="image" type="file" accept="image/*" class="mt-1 block w-full text-sm text-gray-600 file:mr-4 file:rounded-lg file:border-0 file:bg-indigo-50 file:px-3 file:py-2 file:font-semibold file:text-indigo-700 hover:file:bg-indigo-100"><p class="mt-1 text-xs text-gray-500">JPG, PNG, WEBP, maksimal 2 MB.</p><x-input-error :messages="$errors->get('image')" class="mt-2" /></div>
    <div class="sm:col-span-2"><label for="description" class="text-sm font-medium text-gray-700">Deskripsi</label><textarea id="description" name="description" rows="5" class="mt-1 block w-full rounded-lg border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500" required>{{ old('description', $product->description ?? '') }}</textarea><x-input-error :messages="$errors->get('description')" class="mt-2" /></div>
    <div><label for="price" class="text-sm font-medium text-gray-700">Harga (Rp)</label><input id="price" name="price" type="number" min="1" step="1" value="{{ old('price', $product->price ?? '') }}" class="mt-1 block w-full rounded-lg border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500" required><x-input-error :messages="$errors->get('price')" class="mt-2" /></div>
    <div><label for="stock" class="text-sm font-medium text-gray-700">Stok</label><input id="stock" name="stock" type="number" min="0" step="1" value="{{ old('stock', $product->stock ?? '') }}" class="mt-1 block w-full rounded-lg border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500" required><x-input-error :messages="$errors->get('stock')" class="mt-2" /></div>
</div>
<div class="mt-7 flex justify-end gap-3"><a href="{{ route('seller.products.index') }}" class="rounded-lg border border-gray-300 px-4 py-2 text-sm font-semibold text-gray-700 hover:bg-gray-50">Batal</a><button type="submit" class="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white hover:bg-indigo-500">{{ $submitLabel }}</button></div>
